enum Feat {
    endurance = 'endurance',
    diehard = 'diehard',
    fleet = 'fleet',
    leadership = 'leadership',
    nimbleMoves = 'nimbleMoves',
    acrobaticSteps = 'acrobaticSteps',
    run = 'run',
    greatFortitude = 'greatFortitude',
    improvedGreatFortitude = 'improvedGreatFortitude',
    ironWill = 'ironWill',
    improvedIronWill = 'improvedIronWill',
    lightningReflexes = 'lightningReflexes',
    improvedLightningReflexes = 'improvedLightningReflexes',
    extraKi = 'extraKi',
    // TODO Define corresponding class features to enable these feats:
    // extraLayOnHands = 'extraLayOnHands',
    // extraMercy = 'extraMercy',
    // extraPerform = 'extraPerform',
    extraRage = 'extraRage',
    // improvedFamiliar = 'improvedFamiliar',
    channelAlignment = 'channelAlignment',
    commandUndead = 'commandUndead',
    elementalChannel = 'elementalChannel',
    extraChannel = 'extraChannel',
    improvedChannel = 'improvedChannel',
    selectiveChannel = 'selectiveChannel',
    turnUndead = 'turnUndead',
    channelSmite = 'channelSmite',
    combatCasting = 'combatCasting',
    eschewMaterials = 'eschewMaterials',
    improvedCounterspell = 'improvedCounterspell',
    // Removed: spellMastery
    // Removed, new score: spellPenetration
    scribeScroll = 'scribeScroll',
    brewPotion = 'brewPotion',
    craftWondrousItem = 'craftWondrousItem',
    craftArmsArmor = 'craftArmsArmor',
    craftWand = 'craftWand',
    craftRing = 'craftRing',
    craftRod = 'craftRod',
    craftStaff = 'craftStaff',
}

export { Feat };
