name: Coverage

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Yarn install
              uses: Borales/actions-yarn@v5.0.0
              with:
                  cmd: install
            - name: Set up Java 21 zulu
              uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: '21'
            - name: Yarn test (with coverage)
              uses: Borales/actions-yarn@v5.0.0
              with:
                  cmd: coverage
