name: Coverage

on: [push]

jobs:
    coverage-report:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js 20
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Yarn install
              uses: Borales/actions-yarn@v5.0.0
              with:
                  cmd: install
            - name: Yarn test (with coverage)
              uses: Borales/actions-yarn@v5.0.0
              with:
                  cmd: jest-coverage
            - name: Run codacy-coverage-reporter
              uses: codacy/codacy-coverage-reporter-action@v1
              with:
                  project-token: ${{ secrets.CODACY_API_TOKEN }}
                  coverage-reports: ./coverage/lcov.info
